version: "3.9"
services:
  postgres:
    container_name: bc-postgres
    image: bc-postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

